[package]
name = "restaurant_review_dapp"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh ={ version = "1.5.7", features = ["derive"]}
solana-program = "2.1.22"
thiserror = "2.0.12"

[dev-dependencies]
solana-program-test = "2.1.22"
